### ISSUE TITLE
The absence of DECODE env variable breaks the application

### ISSUE THREAD

**Issue by volodymyr-nexxt** [eskimo220/email----slack#4]
[The latest commit](d4234acd6741a73bd98973d2d40eac18402f0e64) introduced `DECODE` env variable, however, the README.md hasn't been updated. 

Therefore, if you don't have `DECODE` in your env variables, this code will break:
https://github.com/eskimo220/email----slack/blob/d4234acd6741a73bd98973d2d40eac18402f0e64/index.js#L15-L16

Since `decode` is `undefined` and trying to access its array element (`decode[0]`) will lead to the unhandled JS error. 

To resolve this issue:
1. Update [README.md](decode[0])
2. Check for `process.env.DECODE` existence in code.

**Comment by nbrons** [comment]
what is the value of process.env.DECODE supposed to be?

**Comment by eskimo220** [comment]
https://github.com/eskimo220/email----slack/commit/182350032105af6bf92a837001fbb4ffcde95fd1

Thank you for reply.I just fix this error.

**Comment by eskimo220** [comment]
https://github.com/eskimo220/email----slack#new-features
@nbrons
